apiVersion: v1
kind: Service
metadata:
  name: lab-aks-service
  labels:
    app: lab-aks-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: lab-aks-service